name: Deploy

# This workflow will only be triggered when the CI workflow that runs on the main branch is complete
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-pdf:
    runs-on: ubuntu-latest
    # if: ${{ (github.event_name == 'push') }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: doc/main.tex
      - uses: actions/upload-artifact@v2
        name: Upload PDF to current workflow
        with:
          name: PDF
          path: main.pdf
      - name: Deploy PDF to remote host
        run: |
          echo ${{ secrets.MY_PW }} > pf.txt
          chmod 0400 pf.txt
          sshpass -f pf.txt scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" main.pdf ${{ secrets.MY_USER }}@${{ secrets.MY_MACHINE }}:/nfs/student/x/${{ secrets.MY_USER }}/public_html/tmp/github-action-example.pdf
